[package]
name = "email-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
lettre = "0.11.7"
dotenvy = "0.15.1"

[build-dependencies]
tonic-build = "0.11"
